### ISSUE TITLE
Way to push custom data on errors

### ISSUE THREAD

**Issue by katzj** [ratchetio/django-ratchet#3]
Have you guys considered hooks for being able to push app-specific data up along with the tracebacks on error?  For example, we're using django-waffle and so being able to report on which feature flags are enabled for a given request is very useful.

I've hacked something up with my own middleware wrapping RatchetNotifierMiddleware but seems like something that could be generally useful.  At the very least adding a hook in the middleware of something like 

``` python
def _add_custom_data(self, request):
   # have custom stuff? subclass RatchetNotifierMiddleware and add this method and get 
   # custom data sent along with your error reports
   return {}
```

that gets called from _build_payload() so that subclasses don't have to do a json decode/re-encode cycle would be helpful

**Comment by coryvirok** [comment]
Hi Jeremy,

That sounds like a great idea. We've built this into the API but haven't exposed it in the Django notifier yet.

We could implement this in a few different ways. Would you prefer:
- subclassing RatchetNotifierMiddleware and overriding a method, (like you mentioned above?)
- passing in a function to the constructor of RatchetNotifierMiddleware which would be passed the current request and exception, (if there is one) and which would return a dictionary containing your custom data?
- handling the notifications directly, (i.e. not using a middleware for it?)
  - We're going to be updating the django-ratchet repo to use our generic python API, [pyratchet](https://github.com/ratchetio/pyratchet) which will allow you direct access to be able to send ratchet.io whatever types of data you'd like. Is this something that you would find useful?

**Comment by katzj** [comment]
The first is probably the most pythonic.  Not sure offhand of an easy way to be able to hook into the middleware init sequence to be able to pass in a function to act as a hook.  I guess it could be done with a setting pointing to the function but that just feels like it's going to be more error prone. The third just means I'm going to write a new middleware (/ forking this one) which isn't all that helpful :)

Where in the data body should custom stuff live -- I don't see it from a quick look in the docs.  But I can hook up a method override pretty easily if I know where the data belongs while I wait on some map/reduce jobs to run.

**Comment by coryvirok** [comment]
The quick and dirty way to include things specific to a request in the
instances table UI is to just put it into the request dict within the
payload. We flatten that dict and show every key in the instances table.

I just read through our docs again and you're right. It's not very apparent
how to do this. I've filed a task to update the docs and also take another
look at our schema to make custom data easier to include.
